// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjjngPxja_ybf9z-2jQbcoVwAJl-kKIlQ',
    appId: '1:565082023487:android:d06df83f2099f596563a8a',
    messagingSenderId: '565082023487',
    projectId: 'pfe-empan-tunisie',
    storageBucket: 'pfe-empan-tunisie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1JQiG2My9okYh7aahpAQZ8dTzg1RNCSQ',
    appId: '1:565082023487:ios:905f8e93b7e3a55f563a8a',
    messagingSenderId: '565082023487',
    projectId: 'pfe-empan-tunisie',
    storageBucket: 'pfe-empan-tunisie.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0j8Rl8t7FjjdDGqaYu_WTB4MI0__1RIo',
    appId: '1:565082023487:web:1c9a3ed2d197748a563a8a',
    messagingSenderId: '565082023487',
    projectId: 'pfe-empan-tunisie',
    authDomain: 'pfe-empan-tunisie.firebaseapp.com',
    storageBucket: 'pfe-empan-tunisie.firebasestorage.app',
    measurementId: 'G-SRR39V5WWW',
  );
}
