import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../localization.dart';
import 'dsm48_encodage.dart';
import 'dsm48_set_page.dart';

class Dsm48MenuPage extends StatelessWidget {
  final String patientDocId;
  final String patientIdentifier;

  const Dsm48MenuPage({
    super.key,
    required this.patientDocId,
    required this.patientIdentifier,
  });

  static const List<String> _set1Types = [
    'Double',
    'Unique',
    'Unique',
    'Double',
    'Abstrait',
    'Double',
    'Unique',
    'Unique',
    'Unique',
    'Abstrait',
    'Unique',
    'Abstrait',
    'Abstrait',
    'Unique',
    'Double',
    'Abstrait',
    'Double',
    'Unique',
    'Unique',
    'Double',
    'Double',
    'Abstrait',
    'Double',
    'Abstrait',
    'Double',
    'Abstrait',
    'Double',
    'Unique',
    'Double',
    'Abstrait',
    'Unique',
    'Abstrait',
    'Unique',
    'Unique',
    'Abstrait',
    'Double',
    'Abstrait',
    'Unique',
    'Double',
    'Abstrait',
    'Unique',
    'Abstrait',
    'Double',
    'Unique',
    'Abstrait',
    'Double',
    'Abstrait',
    'Double',
  ];

  static const List<String> _set1Answers = [
    'A',
    'B',
    'B',
    'B',
    'A',
    'A',
    'B',
    'A',
    'B',
    'B',
    'A',
    'A',
    'A',
    'B',
    'B',
    'A',
    'B',
    'A',
    'B',
    'A',
    'B',
    'B',
    'A',
    'B',
    'B',
    'A',
    'A',
    'B',
    'A',
    'A',
    'B',
    'A',
    'B',
    'B',
    'A',
    'A',
    'A',
    'B',
    'B',
    'A',
    'B',
    'B',
    'A',
    'B',
    'A',
    'B',
    'A',
    'A',
  ];

  static const List<String> _set2Types = [
    'Abstrait',
    'Unique',
    'Unique',
    'Double',
    'Double',
    'Double',
    'Abstrait',
    'Double',
    'Unique',
    'Unique',
    'Double',
    'Abstrait',
    'Unique',
    'Abstrait',
    'Abstrait',
    'Abstrait',
    'Abstrait',
    'Unique',
    'Abstrait',
    'Abstrait',
    'Double',
    'Double',
    'Unique',
    'Unique',
    'Abstrait',
    'Double',
    'Abstrait',
    'Double',
    'Abstrait',
    'Double',
    'Double',
    'Abstrait',
    'Double',
    'Unique',
    'Unique',
    'Abstrait',
    'Abstrait',
    'Unique',
    'Unique',
    'Unique',
    'Double',
    'Double',
    'Double',
    'Abstrait',
    'Double',
    'Unique',
    'Unique',
    'Unique',
  ];

  static const List<String> _set2Answers = [
    'A',
    'B',
    'A',
    'B',
    'B',
    'A',
    'B',
    'A',
    'A',
    'B',
    'B',
    'A',
    'A',
    'B',
    'A',
    'B',
    'A',
    'B',
    'B',
    'A',
    'B',
    'B',
    'B',
    'A',
    'A',
    'A',
    'B',
    'A',
    'B',
    'B',
    'B',
    'A',
    'B',
    'A',
    'B',
    'A',
    'A',
    'B',
    'A',
    'A',
    'A',
    'B',
    'A',
    'B',
    'A',
    'B',
    'A',
    'B',
  ];

  static const List<String> _set3Types = [
    'Double',
    'Abstrait',
    'Unique',
    'Abstrait',
    'Abstrait',
    'Unique',
    'Double',
    'Unique',
    'Double',
    'Abstrait',
    'Unique',
    'Abstrait',
    'Unique',
    'Double',
    'Unique',
    'Abstrait',
    'Double',
    'Unique',
    'Double',
    'Unique',
    'Abstrait',
    'Abstrait',
    'Unique',
    'Double',
    'Double',
    'Double',
    'Abstrait',
    'Abstrait',
    'Abstrait',
    'Abstrait',
    'Double',
    'Double',
    'Abstrait',
    'Double',
    'Abstrait',
    'Double',
    'Abstrait',
    'Unique',
    'Double',
    'Abstrait',
    'Unique',
    'Unique',
    'Unique',
    'Unique',
    'Double',
    'Double',
    'Unique',
    'Unique',
  ];

  static const List<String> _set3Answers = [
    'B',
    'B',
    'A',
    'B',
    'A',
    'A',
    'B',
    'B',
    'A',
    'B',
    'A',
    'A',
    'B',
    'A',
    'A',
    'B',
    'A',
    'B',
    'A',
    'B',
    'A',
    'A',
    'B',
    'A',
    'A',
    'A',
    'B',
    'A',
    'B',
    'B',
    'B',
    'A',
    'B',
    'B',
    'A',
    'B',
    'B',
    'A',
    'A',
    'B',
    'A',
    'B',
    'B',
    'A',
    'B',
    'A',
    'B',
    'A',
  ];

  @override
  Widget build(BuildContext context) {
    final loc = AppLocalizations.of(context);

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: Text(
          loc.dsm48Title,
          style: GoogleFonts.cairo(color: Colors.black),
        ),
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.black),
      ),
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              loc.chooseTest,
              textAlign: TextAlign.center,
              style: GoogleFonts.cairo(
                fontSize: 28,
                fontWeight: FontWeight.bold,
                color: Colors.teal,
              ),
            ),
            const SizedBox(height: 40),
            _buildTestButton(
              context,
              loc.dsm48MenuEncodage,
              Icons.visibility,
              () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => Dsm48EncodagePage(
                    patientDocId: patientDocId,
                    patientIdentifier: patientIdentifier,
                  ),
                ),
              ),
            ),
            const SizedBox(height: 20),
            _buildTestButton(
              context,
              loc.dsm48MenuSet1,
              Icons.quiz,
              () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => Dsm48SetPage(
                    patientDocId: patientDocId,
                    patientIdentifier: patientIdentifier,
                    setIndex: 1,
                    correctAnswers: _set1Answers,
                    itemTypes: _set1Types,
                    setLabel: loc.dsm48MenuSet1,
                  ),
                ),
              ),
            ),
            const SizedBox(height: 20),
            _buildTestButton(
              context,
              loc.dsm48MenuSet2,
              Icons.quiz_outlined,
              () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => Dsm48SetPage(
                    patientDocId: patientDocId,
                    patientIdentifier: patientIdentifier,
                    setIndex: 2,
                    correctAnswers: _set2Answers,
                    itemTypes: _set2Types,
                    setLabel: loc.dsm48MenuSet2,
                  ),
                ),
              ),
            ),
            const SizedBox(height: 20),
            _buildTestButton(
              context,
              loc.dsm48MenuSet3,
              Icons.quiz_rounded,
              () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => Dsm48SetPage(
                    patientDocId: patientDocId,
                    patientIdentifier: patientIdentifier,
                    setIndex: 3,
                    correctAnswers: _set3Answers,
                    itemTypes: _set3Types,
                    setLabel: loc.dsm48MenuSet3,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTestButton(
    BuildContext context,
    String title,
    IconData icon,
    VoidCallback onTap,
  ) {
    return ElevatedButton(
      onPressed: onTap,
      style: ElevatedButton.styleFrom(
        backgroundColor: Colors.teal,
        foregroundColor: Colors.white,
        padding: const EdgeInsets.symmetric(vertical: 20),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
        elevation: 3,
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(icon, size: 28),
          const SizedBox(width: 15),
          Text(
            title,
            style: GoogleFonts.cairo(fontSize: 20, fontWeight: FontWeight.bold),
          ),
        ],
      ),
    );
  }
}
